[build]
  functions = "functions"

[[redirects]]
  from = "/index"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/index2"
  to = "/index2.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
